// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_QSKdQmOuks7jZA321wtdk8yKaJ50GOA',
    appId: '1:899471675960:web:3b9092a7ec03aa62454ccd',
    messagingSenderId: '899471675960',
    projectId: 'paisabaiproject',
    authDomain: 'paisabaiproject.firebaseapp.com',
    storageBucket: 'paisabaiproject.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA-NoOxzyV8qdmBEj1Z-oAsZaK5BBvwv8',
    appId: '1:899471675960:android:7b733835885ddf5e454ccd',
    messagingSenderId: '899471675960',
    projectId: 'paisabaiproject',
    storageBucket: 'paisabaiproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-0J0zFbZuGv4MZ2nMm8sadrxn26w52nA',
    appId: '1:899471675960:ios:97371700b13bc3d4454ccd',
    messagingSenderId: '899471675960',
    projectId: 'paisabaiproject',
    storageBucket: 'paisabaiproject.firebasestorage.app',
    iosBundleId: 'com.example.paisabaiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-0J0zFbZuGv4MZ2nMm8sadrxn26w52nA',
    appId: '1:899471675960:ios:97371700b13bc3d4454ccd',
    messagingSenderId: '899471675960',
    projectId: 'paisabaiproject',
    storageBucket: 'paisabaiproject.firebasestorage.app',
    iosBundleId: 'com.example.paisabaiApp',
  );
}
